#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/trbjrn/anaconda3/envs/lfpy"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/trbjrn/anaconda3/envs/lfpy/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/trbjrn/Documents/lfpy_master_thesis/x86_64/.libs/libnrnmech.so" "$@"
