#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/trbjrn/anaconda3"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/trbjrn/anaconda3/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/trbjrn/Documents/Master Thesis/ExtStim/ExtStim/cell_models/AberraEtAl2018/x86_64/.libs/libnrnmech.so" "$@"
